### ISSUE TITLE
[Request for Contributions] OP Rewards: Liquidity Staking on Optimism (Lido & Rocket Pool)

### ISSUE THREAD

**Issue by chuxinh** [ethereum-optimism/op-analytics#132]
### Project
Liquidity Staking on Optimism (Lido & Rocket Pool)
### Description
Deep dives to explore the how OP rewards are distributed to incentivise liquidity staking on Optimism, how rewards are allocated across dapps/liquidity pools and their performances, OP and LDO spend, how liquidity retention is looking like in the absence of incentives, and any other recommendations you have

### Find out more
Lido: https://www.notion.so/oplabs/Lido-51c8f1e4a6f24bcd88ca84bba9fc8dfc?pvs=4
Rocketpool: https://www.notion.so/oplabs/Rocket-Pool-260afe3571434634a680d21e006839a7?pvs=4

**Comment by ptagr8** [comment]
this is awesome
