### ISSUE TITLE
[Request for Contributions] OP Rewards:  Arrakis/Gamma Uniswap programs

### ISSUE THREAD

**Issue by chuxinh** [ethereum-optimism/op-analytics#133]
### Project
Arrakis/Gamma Uniswap programs
### Description
Both Arrakis and Gamma have ended their rewards programs and now it is time to dive deeper into understanding the OP rewards impact during and post incentives. 
- How are the DEX volume and TVL change: pre, during and post incentives
- Can DEX volume be further segmented by bots, whales and retail users 
- What's the liquidity retention looking like
- What would you recommend for future programs? 

### Find out more
Arrakis: https://www.notion.so/oplabs/OP-Uniswap-Liquidity-Managers-Arrakis-d05d172649d247a29861e6e2cbcdc0df?pvs=4
Gamma: https://www.notion.so/oplabs/OP-Uniswap-Liquidity-Managers-Gamma-fff4500e003b48c0aa9a16bca5b8e005?pvs=4

**Comment by mishchenkoy** [comment]
👌💪

**Comment by raho11** [comment]
Hello, I've begun this analysis on the Optimism forum [here](https://gov.optimism.io/t/retrospective-funding-analysis-uniswap-v3-liquidity-incentives/6212/3?u=raho) and will update with a new post when Phase 3 ends in late July/early August.
