### ISSUE TITLE
[Request for Contribution] OP Rewards Program Tracking Update

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/op-analytics#46]
Notice a program with information that needs to be updated in the [OP Rewards Program Tracker](https://oplabs.notion.site/26d856d5ad7c4fda919c62e839cf6051?v=4e38174b2e994129b51dcfa127965aa4)? Please report it here:

**Program Name:** *This Should match what's shown on the Tracker*

**Missing/Updated Information:** *Please share the information that needs to be updated & provide links for proof if possible*

**Comment by raho11** [comment]
**Program Name:** Kwenta

**Missing/Updated Information:** New trading rewards program (partnership with Synthetix). 

[Announcement Blog Post](https://mirror.xyz/kwenta.eth/8KyrISnjOcuAX_VW-GxVqxpcbWukB_RlP5XWWMz-UGk)

**Comment by raho11** [comment]
**Program Name:** Mean Finance

**Missing/Updated Information:** Mean Finance early adopter OP Airdrop 

[Announcement Tweet](https://twitter.com/mean_fi/status/1663231135760158720?s=46&t=YuiqYnL-zBGP6cy9xw6MNw)

**Comment by raho11** [comment]
**Program Name:** Boardroom 

**Missing/Updated Information:**

- Boardroom delegation incentivizes via Layer3 on Nov. 1, 2022 (76K OP)
  - [Blog Post](https://layer3.mirror.xyz/lke0sFvr5uL03E7tR0wn_uSqexQptCZAkScH50G8n68)
  - [Tweet](https://twitter.com/layer3xyz/status/1587484251351547905?s=20)

**Comment by raho11** [comment]
**Program Name:** Rabbithole

**Missing/Updated Information:** 
- Optimism Race Program is live
  -  [Blog Post](https://rabbithole.mirror.xyz/x4uSDG699c8MzsvH2rkx_RZHtvMkE8hwll0hquTqE7A)
  - [Tweet](https://twitter.com/rabbithole_gg/status/1658255536142286848?s=20)

**Comment by MSilb7** [comment]
This is awesome @raho11 thanks so much!

> Kwenta
We had Kwenta marked live from earlier small competitions. It seems like this program is from Synthetix Perps, but for now keeping Kwenta as "live" since Aug 10, 2022 (maybe a future iteration/improvement could be to split out each sub-program)

> Mean Finance
Marked as live! Unclear what share of the whole program the airdrop is, but the wording makes it seem like more is coming, so keeping it 'live" vs marking as a 1 day program (as we did with the 1inch airdrop).

> Boardroom
Added, looks like this spent 80k/100k OP, so keeping as "live" since 20k are left to be allocated (unless we see other announcements). This likely would require custom analysis to analyze since it's not through a Boardroom contract (rather we could use Layer3 claim as a method to attribute addresses to the program). + the right metrics are probably "increase in votable supply," "delegation retention," etc rather than normal transactions, gas spend.

> Rabbithole
Added!

**Comment by raho11** [comment]
**Program Name:** Polynomial Protocol

**Missing/Updated Information:** 
Current 'App Type' = 'Options'
Polynomial should be 'App Type' = 'Perpetuals'

**Comment by raho11** [comment]
**Program Name**: PoolTogether #2 

**Missing/Updated Information**:
PoolTogether #2 is marked as completed, but the funding has not been fully distributed. Following prior program status such as Boardroom mentioned above, PoolTogether should not be considered complete. 

The remaining OP are earmarked for: 
- 'teams/projects that build new PoolTogether UIs that leverage core features of the protocol on Optimism'
- 'projects that directly integrate PoolTogether on Optimism'
([Source](https://gov.optimism.io/t/review-gf-phase-1-pooltogether/3747#how-will-the-op-tokens-be-distributed-20))

**Comment by chain-l** [comment]
**Program name:-** Via Protocol  

**Missing Information:** 
Actions Rewarded:- Gas Fee Refund
Announced On:- April 1, 2023 
Announcement Link:- https://twitter.com/via_protocol/status/1642167383203753986?s=20
App Link:- http://router.via.exchange/
App Type:- DEX Aggregator | Bridge
Description:- The app finds the best route for any-to-any swap. It supports multi-chain & works efficiently.
Start Date:- 25-05-2023
Status:- Live
Status - Season:- Live - Governance - Season 3
Additional Links:- 
https://twitter.com/via_protocol/status/1653758003571507203?s=20
https://twitter.com/via_protocol/status/1663175119282241537?s=20
https://twitter.com/via_protocol/status/1698896086893834602?s=20

**Comment by chuxinh** [comment]
@chain-l added and thank you for the help!!
