### ISSUE TITLE
[Request for Contribution] OP Rewards - Liquidity Configuration

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/op-analytics#47]
The liquidity/TVL tracking for the OP rewards program tracker is controlled by [this input file](https://github.com/ethereum-optimism/op-analytics/blob/main/op_rewards_tracking/inputs/op_incentive_protocols.csv) in `op_rewards_tracking/inputs`.

As new programs launch / end / modify, this csv needs to be updated to reflect that. This includes the slug (if Defillama), program name (for joining - if there's a relevant sub-program), the start date & end date, op source, data source, contracts (if via subgraphs), and other fields.

If information needs to be updated, you can comment on this issue and/or make a PR to propose updates.

**Comment by Joykel** [comment]
New
