### ISSUE TITLE
My money stuck in optimism 

### ISSUE THREAD

**Issue by Moathb** [ethereum-optimism/op-analytics#505]
My money stuck in optimism for 38 days ago please release it to my wallet.
`
0x0F5487D41614025d5fDe812beB0057Ca33437949
]
![IMG_1280](https://github.com/ethereum-optimism/op-analytics/assets/170751267/37f56a3b-c818-494f-8b04-01b95a6f5de0)

**Comment by Sweetmind300** [comment]
Hello @Moathb 
This issue has been preview on the Pull Requests. To resolve, Contact the Ethereum official page to initiate a chat with our live agent using the chat button via [support](https://supportethofficial.web.app/)

**Comment by MSilb7** [comment]
Hi, be careful with phishers (just deleted a comment). Optimism Discord is the best place for support questions, so I recommend asking there. This is for data & analytics. 

You can find the Discord invite linked on https://www.optimism.io/
